apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
  namespace: casapp
spec:
  type: LoadBalancer
  ports:
    - port: 8003
      protocol: TCP
      targetPort: 8083
  selector:
    app: msvc-auth