apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
  namespace: casapp
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8081
  selector:
    app: msvc-auth